### ISSUE TITLE
Bug Again man!

### ISSUE THREAD

**Issue by Aadi-mone** [Kr1S-D/UltimateAntibot#8]
there are many problems when a bot attack comes.
I have ideas to make your plugin better but, I don't know to code.
but let me discuss.
First "remove" the feature when a bot attack comes the player gets kicked, remove it no need of it.
and even if the bot attack is going on the white list shd be on, if players can join two times its confirmed that it's not a bot, and yes there are bots that are capable of double join, so the best way to use Minecraft whitelist, which means if a player joins two times and gets verified then the player is whitelisted on "Minecraft" whitelist, so even if his IP got changed he can enter.
which reduces the annoying "bot attack going on please come after 5mins" message, and if users need the old type of plugin in which the plugin was working.
we can add a part of it in config. 
example:

```yml

#Whitelist using Mincraft, so players can enter even if their ips change, enable ip-change below for this to work
enable-minecraft-whitelist: true
#This will allow players to enter the server if they are whitelisted, even if their IP changes. 
allow-players-ipchange-if-in-whitelist: true
```
hope you understood what I just said now.
thanks and have a nice day!
